# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


  lane :internaltravis do
    sh('git fetch --tags')
    build_version = last_git_tag
    version_code = get_version_code
     gradle(
       task: 'assemble',
       build_type: 'Release',properties: {'versionName': build_version,
     "android.injected.signing.store.file" => "app/key.jks",
    'android.injected.signing.store.password' => ENV["KEYSTORE_PASSWORD"],
    'android.injected.signing.key.alias'=> ENV["KEYSTORE_ALIAS"],
    'android.injected.signing.key.password' => ENV["KEYSTORE_ALIAS_PASSWORD"]})

          change_log = read_changelog(
           changelog_path: '../CHANGELOG.md',
           section_identifier: '[Unreleased]',
           excluded_markdown_elements: ['###']
           )
            File.open("./metadata/android/en-US/changelogs/#{version_code}.txt", 'w+') do |file|
              file.write change_log
            end
           upload_to_play_store(track: 'internal',skip_upload_images: true,skip_upload_screenshots: true,
           json_key_data: ENV['PLAYSTORE_DATA'],
           apk: '../build/app/outputs/apk/release/app-release.apk')
  end

    lane :internal do |options|
    build_version = options[:build]
    version_code = options[:version]
              change_log = read_changelog(
               changelog_path: '../CHANGELOG.md',
               section_identifier: '[Unreleased]',
               excluded_markdown_elements: ['###']
               )
                File.open("./metadata/android/en-US/changelogs/#{version_code}.txt", 'w+') do |file|
                  file.write change_log
                end
           gradle(
             task: 'assemble',
             build_type: 'Release')
             upload_to_play_store(track: 'internal',skip_upload_images: true,skip_upload_screenshots: true,
             json_key: "app/google-play-console.json",
             apk: '../build/app/outputs/apk/release/app-release.apk')
           stamp_changelog(
                  section_identifier: "Build #{build_version}",
                  changelog_path: '../CHANGELOG.md',
                  git_tag: last_git_tag)
    end



  lane :prep do |options|
    build_version = options[:build]
    stamp_changelog(
           section_identifier: "Build #{build_version}",
           changelog_path: '../CHANGELOG.md',
           git_tag: last_git_tag)
  end

end

